### ISSUE TITLE
Logo and favicon 

### ISSUE THREAD

**Issue by carlaberkers** [canonical-webteam/practices#110]
Favicon currently missing.

For the logo should we use the Canonical logo? Or better Ubuntu? Or make something new?
The owl is cute but an out of date pictogram we are no longer using.

Be good to hear thoughts on this.

**Comment by nottrobin** [comment]
I like the idea of something new if a designer has time to create it. I think it should be more Canonical than Ubuntu.

**Comment by kwm14** [comment]
@carlaberkers @nottrobin I can take a look at this 👍

**Comment by nottrobin** [comment]
@kwm14 would it be possible to base the logo off the Canonical brand rather than the Ubuntu brand? There's an ongoing discussion about trying to tie disparate products back to our corporate brand, and reduce the pollution of the Ubuntu brand with stuff that isn't directly about the operating system. I was hoping this could form a sort of first step towards trying to move in that direction.

**Comment by nottrobin** [comment]
@kwm14 also bear in mind https://github.com/canonical-webteam/practices/issues/109 - "Web and design team practices"

**Comment by kwm14** [comment]
## Quick exploration
Using Canonical brand rather than Ubuntu.

### 001
![visual-001](https://user-images.githubusercontent.com/17748020/48839750-63c32700-ed84-11e8-9dcd-2aa1dbda9c50.png)

### 002
![visual-002](https://user-images.githubusercontent.com/17748020/48839751-63c32700-ed84-11e8-87df-b3b5f526490d.png)

### 003
![visual-004](https://user-images.githubusercontent.com/17748020/48839754-645bbd80-ed84-11e8-8aa9-909f2829d5b3.png)

### 004
![visual-005](https://user-images.githubusercontent.com/17748020/48839755-645bbd80-ed84-11e8-9b8d-23fd388d8f80.png)

**Comment by nottrobin** [comment]
Quick work @kwm14! I think I like 1 and 4 - the "CANONICAL" word is a bit loud and garish next to the title. Maybe I'm leaning towards 4?

**Comment by kwm14** [comment]
@nottrobin agree that "CANONICAL" word is loud and potentially looks disconnected from 'Web and design team practices'

Quick solution would be **001** and replacing the owl with our Canonical circle - https://assets.ubuntu.com/v1/60d9b81e-picto-canonical.svg

I also like **004** but not sure how complicated that is to do in code, I guess we can strip the code styling applied to https://www.ubuntu.com/ navigation

**Comment by nottrobin** [comment]
@kwm14 okay I'll just replace the logo with https://assets.ubuntu.com/v1/60d9b81e-picto-canonical.svg for now. We can evolve this down the line.
